tasks/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.task_list, name="list"),
    path('task_done/<int:pk_done>', views.task_done, name="done"),
    path('task_delete/<int:pk>', views.task_delete, name="delete"),
    path('create/', views.task_create, name="create"),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from tasks import views as task_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('', task_views.task_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()

tasks/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    #true -> the task will be displayed
    #false -> will be stored in DB, but not displayed
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    

tasks/views.py
from django.shortcuts import render, redirect
from .models import Task
# Create your views here.

def task_list(request):
    tasks = Task.objects.all().order_by('date')

    return render(request,'tasks/task_list.html',{'tasks': tasks})

def task_delete(request, pk):
    task = Task.objects.get(pk=pk)
    task.delete()
    return redirect('home')

def task_done(request, pk_done):
    task = Task.objects.get(pk=pk_done)
    task.active = False
    task.save(update_fields=["active"])
    return redirect('home')

def task_create(request):
    if request.method == 'POST':
        task = Task(title = request.POST['title'])
        task.save()
    return redirect('home')

tasks/templates/tasks/task_list.html
{% extends 'base_layout.html' %}   

{% block content %}
   <h1>Tasks list</h1>

   <div class="create-task">
    <h2>Create new task</h2>
    <form class="site-form" action="{% url 'tasks:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="title">
        <input type="submit" value="Add">
    </form>
    </div>

    <div class="tasks-list">
        {% for task in tasks %}
            {% if task.active %}
            <div class="task-pending">
                <p>{{task.title}}</p>
                <p>{{task.date}}</p>
                <p>Status : Pending</p>
                <a href="{% url 'tasks:delete' task.pk %}">Delete</a>
                <a href="{% url 'tasks:done' task.pk %}">Finish</a>
            </div>
            {% else %}
            <div class="task-done">
                <p>{{task.title}}</p>
                <p>{{task.date}}</p>
                <p>Status : Done</p>
                <a href="{% url 'tasks:delete' task.pk %}">Delete</a>
            </div>
            {% endif %}
        {% endfor %}
        </div>
{% endblock %}

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header class="wrapper">
        <nav>
            
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>